server {
    listen 8080;
    server_name _;

    location = /api/products {
        proxy_pass http://api:8080/api/products;
    }

    location = /api/products/reservations {
        proxy_pass http://api:8080/api/products/reservations;
    }

    location ^~ /api/ {
        return 404;
    }
}
